package com.regaltec.asip.transport.soap.cxf.ida40;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2011-03-10T18:03:37.861+08:00
 * Generated source version: 2.3.3
 * 
 */
 
@WebService(targetNamespace = "http://www.regaltec.com.cn/ida40", name = "AsipServicePort")
@XmlSeeAlso({ObjectFactory.class})
public interface AsipServicePort {

    @ResponseWrapper(localName = "callResponse", targetNamespace = "http://www.regaltec.com.cn/ida40", className = "com.regaltec.asip.transport.soap.cxf.ida40.CallResponse")
    @RequestWrapper(localName = "call", targetNamespace = "http://www.regaltec.com.cn/ida40", className = "com.regaltec.asip.transport.soap.cxf.ida40.Call")
    @WebResult(name = "result", targetNamespace = "")
    @WebMethod
    public java.lang.String call(
        @WebParam(name = "serviceName", targetNamespace = "")
        java.lang.String serviceName,
        @WebParam(name = "serviceClass", targetNamespace = "")
        java.lang.String serviceClass,
        @WebParam(name = "parameterXML", targetNamespace = "")
        java.lang.String parameterXML,
        @WebParam(name = "contextName", targetNamespace = "")
        java.lang.String contextName
    );
}
